### ISSUE TITLE
'Feather file footer incomplete' 

### ISSUE THREAD

**Issue by CurlyZhu** [snakers4/emoji-sentiment-dataset#1]
Hi, thank you for your contribution!
When I load the data with feather.read_dataframe() in Python, I get the error message "Feather file footer incomplete". I'm not quite familiar with feather files, and I'm not sure if I missed out something or if something's wrong with the file. Would you please check out the format or provide some more details for running? Thanks a lot!

**Comment by snakers4** [comment]
Hi,

Does the error persist with this?
```
import pandas as pd
df = pd.read_feather(path)
```

Also btw this dataset seems too small to provide a sensible sentiment classifier - as opposed to 1bn tweets with emojis in the original paper.
So we decided to abandon it.

**Comment by CurlyZhu** [comment]
All Right. Seems it works fine with the pandas code. Thanks again.
