### ISSUE TITLE
process_tweets.py not found

### ISSUE THREAD

**Issue by ghost** [snakers4/emoji-sentiment-dataset#2]
Hi,

Hope you are all well !

Files referenced in the README are not available, for example:
https://github.com/snakers4/emoji_sentiment/blob/master/src/process_tweets.py

Any ways to get them online ?

Cheers,
X

**Comment by snakers4** [comment]
Which exact files do you mean?

**Comment by ghost** [comment]
The one mention above

**Comment by ghost** [comment]
Maybe the repo is private also...

**Comment by snakers4** [comment]
made it public
